default: &default
  database: <%= ENV.fetch('JOBLINGE_DB_NAME', 'joblinge') %>
  timeout: 5000
  adapter: postgresql
  encoding: unicode
  pool:     <%= ENV.fetch('JOBLINGE_DB_POOL_SIZE', 25) %>
  username: <%= ENV.fetch('JOBLINGE_DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('JOBLINGE_DB_PASSWORD', 'postgres') %>
  host:     <%= ENV.fetch('JOBLINGE_DB_HOSTNAME', 'localhost') %>
  port:     <%= ENV.fetch('JOBLINGE_DB_PORT',     '5432') %>

development:
  <<: *default

test:
  <<: *default
  database: joblinge_test

production:
  <<: *default
